# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
aliases:
    co: pr checkout
    prco: "!gh pr checkout $(GH_FORCE_TTY=49% gh pr list | fzf --no-sort --ansi --preview \"GH_FORCE_TTY=1 CLICOLOR_FORCE=1 gh pr view {1}\" | awk '{split($1,a); print a[1]}')"
    prv: "!gh pr view --web"
    b: branch
